In [1]:
import numpy as np #numpy array

In [2]:
my_list = [1,2,3]

In [3]:
np.array(my_list)

array([1, 2, 3])

In [4]:
my_metrix = [[1,2,3],[4,5,6],[7,8,9]]

In [5]:
my_metrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [6]:
np.array(my_metrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
#Built-in Methods

#arrange

#0 - 10

np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [12]:
#zeros

np.zeros(3)

array([0., 0., 0.])

In [14]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [15]:
#ones

np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [17]:
#linspace

np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [18]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [21]:
#eye

np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [25]:
#Random

#rand

np.random.rand(2)

array([0.11226705, 0.68794228])

In [26]:
np.random.rand(10) * 10

array([6.85633048, 3.81890465, 9.65490444, 6.23386378, 7.80198962,
       1.76844754, 4.25803597, 4.47891924, 4.64841258, 5.49029574])

In [27]:
np.random.rand(5,5)

array([[0.21175754, 0.27633338, 0.2246185 , 0.79269368, 0.02504736],
       [0.47411289, 0.17430907, 0.67077116, 0.69754068, 0.71025003],
       [0.73607893, 0.59010976, 0.14838685, 0.74004937, 0.17659859],
       [0.40840529, 0.05833395, 0.77654035, 0.4061571 , 0.48609376],
       [0.59812065, 0.40375443, 0.39511369, 0.21833557, 0.18221094]])

In [28]:
#randn #(-1,1,)

np.random.randn(2)

array([-1.10534031,  2.36262984])

In [29]:
np.random.randn(5,5)

array([[-0.91232463, -0.24766   ,  0.88598233,  0.69559592, -0.29822117],
       [-0.36157475,  0.79654124,  0.63924386,  1.50643011, -0.67642261],
       [ 0.39185731,  0.59959783,  0.39017351,  0.12664999,  0.60139198],
       [-0.92139527,  0.64028957, -1.89714803, -0.74313577, -0.19154882],
       [ 0.21511896, -0.21977768, -0.46328673, -2.12978107, -0.13866501]])

In [31]:
#randint

np.random.randint(1,100)

86

In [32]:
np.random.randint(1,100,10)

array([74, 88, 14, 27,  4, 85, 72, 26, 21, 55])

In [33]:
#attributes, method

In [38]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [39]:
arr #25

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [40]:
ranarr #10

array([48, 41, 17,  2, 28, 46, 20, 30,  0,  4])

In [41]:
#reshape

In [42]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [43]:
ranarr.reshape(5,2)

array([[48, 41],
       [17,  2],
       [28, 46],
       [20, 30],
       [ 0,  4]])

In [50]:
# max
ranarr

array([48, 41, 17,  2, 28, 46, 20, 30,  0,  4])

In [51]:
ranarr.max()

48

In [52]:
ranarr.argmax()

0

In [53]:
ranarr.min()

0

In [54]:
ranarr.argmin()

8

In [55]:
arr.shape

(25,)

In [56]:
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [59]:
arr.reshape(1,25).shape

(1, 25)

In [60]:
# dtype

In [62]:
arr.dtype

dtype('int32')

In [63]:
#Indexing and Selection

In [64]:
import numpy as np

In [65]:
arr = np.arange(0,11)

In [66]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [69]:
arr[8]

8

In [70]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [71]:
arr[0:5] = 100

arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [73]:
arr = np.arange(0,11)

arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [74]:
slice_of_arr = arr[0:6]

In [75]:
slice_of_arr[:] = 99
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [76]:
slice_of_arr = 99
slice_of_arr

99

In [77]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [78]:
arr_copy = arr.copy()

In [79]:
arr_copy[:] = 1

In [80]:
arr_copy

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [81]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [82]:
#Indexing 2d array (Metrices)

In [83]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

In [84]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [85]:
arr_2d[1][0] # [row][col]

20

In [87]:
arr_2d[0:2,0:2]

array([[ 5, 10],
       [20, 25]])

In [88]:
arr_2d[1][:]

array([20, 25, 30])

In [103]:
arr_2d[2][:]

array([35, 40, 45])

In [107]:
arr_2d[:][1]

array([20, 25, 30])

In [109]:
arr2d = np.zeros((10,10))

In [110]:
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [111]:
arr_length = arr2d.shape[1]

In [112]:
arr_length

10

In [114]:
for i in range (arr_length):
    arr2d[i] = i #col
    
arr2d


array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [115]:
#Selection

In [116]:
arr = np.arange(1,11)

In [117]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [118]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [119]:
bool_arr = arr > 4

In [120]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [121]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [126]:
x = 7
arr[arr > x]

array([ 8,  9, 10])

In [127]:
#Numpy Operation

In [128]:
import numpy as np
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [129]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [130]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [131]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [132]:
arr / arr

C:\Users\Psungg\AppData\Local\Temp\ipykernel_26896\3001117470.py:1: RuntimeWarning: invalid value encountered in divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [135]:
1 / arr

C:\Users\Psungg\AppData\Local\Temp\ipykernel_26896\1528351372.py:1: RuntimeWarning: divide by zero encountered in divide
  1 / arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [136]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [137]:
arr ** 3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [138]:
arr = np.arange(0,10)

In [139]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [140]:
np.max(arr)

9

In [141]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [142]:
np.log(arr)

C:\Users\Psungg\AppData\Local\Temp\ipykernel_26896\3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])